# Generated by Django 3.1.6 on 2021-02-07 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='UserName',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Passwort',
            new_name='Password',
        ),
    ]
